<a href="https://colab.research.google.com/github/ReddimiSaiReddy9/PythonCourseEminence/blob/master/ReddyPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

E1


In [21]:
import numpy as np
array = np.arange(10)
array




array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

E2

In [22]:
odd_no=array[array%2==1]
odd_no

array([1, 3, 5, 7, 9])

E3

In [23]:
array[array%2==1]=-1
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

E4

In [31]:
arr = np.reshape(array, (2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

E5

In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_item= np.intersect1d(a, b)
common_item

array([2, 4])

E6

In [4]:
import numpy as np
a = np.array([2,6,1,9,10,3,27])
a[(a>4) & (a<11)]


array([ 6,  9, 10])

E7

In [13]:
import numpy as np
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652], [0.54627315, 0.05093587, 0.40067661, 0.55645993], [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
sum_a = a.sum()
maxvalue_a = a.max()
print(sum_a)
print(maxvalue_a)

4.8595784
0.82485143


E8

In [22]:
import numpy as np
def multiply():
  a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
            [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]]) 
  m=10*a
  return m
multiply()

array([[4.5053314, 1.7296777, 3.4376245, 5.510652 ],
       [5.4627315, 0.5093587, 4.0067661, 5.5645993],
       [1.2697628, 8.2485143, 2.6590556, 5.6917101]])

E9

In [2]:
import pandas as pd
log_data = pd.read_csv('https://raw.githubusercontent.com/Energy-AI/basic_course/master/Lecture_3/data/log_data_csv.csv?token=AQU7K5GPIRBWHBOFF4CU37C7MTV4C')
log_data.set_index('DEPTH', inplace = True)
log_data

ABDCQF01  ABDCQF02  ABDCQF03  ABDCQF04  ...      ROP  RPCEHM  RPCELM  RT
DEPTH                                           ...                             
145.9        NaN       NaN       NaN       NaN  ...      NaN     NaN     NaN NaN
146.0        NaN       NaN       NaN       NaN  ...      NaN     NaN     NaN NaN
146.1        NaN       NaN       NaN       NaN  ...      NaN     NaN     NaN NaN
146.2        NaN       NaN       NaN       NaN  ...      NaN     NaN     NaN NaN
146.3        NaN       NaN       NaN       NaN  ...      NaN     NaN     NaN NaN
...          ...       ...       ...       ...  ...      ...     ...     ...  ..
3464.5       NaN       NaN       NaN       NaN  ...  29.9836     NaN     NaN NaN
3464.6       NaN       NaN       NaN       NaN  ...  29.9767     NaN     NaN NaN
3464.7       NaN       NaN       NaN       NaN  ...  29.9699     NaN     NaN NaN
3464.8       NaN       NaN       NaN       NaN  ...  29.9903     NaN     NaN NaN
3464.9       NaN       NaN       NaN       NaN  ...      NaN     NaN     NaN NaN

[33191 rows x 22 columns]

E10

In [3]:
bs = log_data['BS']
col = bs.to_numpy()
col

array([36. , 36. , 36. , ...,  8.5,  8.5,  8.5])

E11

In [4]:
log_data['BS'].value_counts()

17.5000    12469
26.0000    11289
12.2500     4827
8.5000      3800
36.0000      800
12.2283        2
8.5217         1
25.9508        1
17.4696        1
35.9421        1
Name: BS, dtype: int64

E12

In [5]:
log_data['BS'].nunique()

10

E13

In [7]:
minimum = log_data['GR'].min()
percentile_25 = log_data['GR'].quantile(0.25)
median = log_data['GR'].median()
percentile_75 = log_data['GR'].quantile(0.75)
print('Minimum is ' + str(minimum))
print('25th Percentile is ' + str(percentile_25))
print('Median is ' + str(median))
print('75th Percentile is ' + str(percentile_75))

Minimum is 0.1493
25th Percentile is 29.481175
Median is 58.005700000000004
75th Percentile is 79.2472


E14

In [8]:
log_data['BS'] = log_data['BS'].replace([36], 40)
log_data['BS']

DEPTH
145.9     40.0
146.0     40.0
146.1     40.0
146.2     40.0
146.3     40.0
          ... 
3464.5     8.5
3464.6     8.5
3464.7     8.5
3464.8     8.5
3464.9     8.5
Name: BS, Length: 33191, dtype: float64

E15

In [17]:
import pandas as pd
production_data = pd.read_csv('https://raw.githubusercontent.com/Energy-AI/basic_course/master/Lecture_3/data/prod_data.csv?token=AQU7K5AP2LVRN325XOLVPK27MTZLS')
del production_data['Unnamed: 0']
production_data

DATEPRD  AVG_DOWNHOLE_PRESSURE  ...   FLOW_KIND  WELL_TYPE
0      2014-04-07                0.00000  ...  production         WI
1      2014-04-08                    NaN  ...  production         OP
2      2014-04-09                    NaN  ...  production         OP
3      2014-04-10                    NaN  ...  production         OP
4      2014-04-11              310.37614  ...  production         OP
...           ...                    ...  ...         ...        ...
15629  2016-09-14                    NaN  ...  production         OP
15630  2016-09-15                    NaN  ...  production         OP
15631  2016-09-16                    NaN  ...  production         OP
15632  2016-09-17                    NaN  ...  production         OP
15633  2016-09-18                    NaN  ...   injection         WI

[15634 rows x 16 columns]

E16

In [18]:
production_data['DATEPRD'] = pd.to_datetime(production_data['DATEPRD'])
production_data['DATEPRD']

0       2014-04-07
1       2014-04-08
2       2014-04-09
3       2014-04-10
4       2014-04-11
           ...    
15629   2016-09-14
15630   2016-09-15
15631   2016-09-16
15632   2016-09-17
15633   2016-09-18
Name: DATEPRD, Length: 15634, dtype: datetime64[ns]

In [20]:
production_data.set_index('DATEPRD', inplace = True)
production_data

AVG_DOWNHOLE_PRESSURE  ...  WELL_TYPE
DATEPRD                            ...           
2014-04-07                0.00000  ...         WI
2014-04-08                    NaN  ...         OP
2014-04-09                    NaN  ...         OP
2014-04-10                    NaN  ...         OP
2014-04-11              310.37614  ...         OP
...                           ...  ...        ...
2016-09-14                    NaN  ...         OP
2016-09-15                    NaN  ...         OP
2016-09-16                    NaN  ...         OP
2016-09-17                    NaN  ...         OP
2016-09-18                    NaN  ...         WI

[15634 rows x 15 columns]

E17

In [23]:
production_data.groupby(pd.Grouper(freq='Y')).sum()

AVG_DOWNHOLE_PRESSURE  ...   BORE_WI_VOL
DATEPRD                            ...              
2007-12-31               0.000000  ...  0.000000e+00
2008-12-31          126332.310680  ...  2.417770e+06
2009-12-31          171879.218917  ...  4.392198e+06
2010-12-31          160502.923169  ...  4.569394e+06
2011-12-31           83850.168072  ...  3.442446e+06
2012-12-31           78690.519824  ...  2.975214e+06
2013-12-31          127489.850406  ...  3.453761e+06
2014-12-31          317179.952517  ...  3.825493e+06
2015-12-31          349952.670812  ...  3.201627e+06
2016-12-31          216721.126936  ...  2.052229e+06

[10 rows x 12 columns]